### ISSUE TITLE
[compat] Google Play Music

### ISSUE THREAD

**Issue by hach-que** [hensm/fx_cast-compat#15]
**App name:** Google Play Music
**App URL:** https://play.google.com/music/listen

**Issues:**
Works, just needs to be added to the whitelist. "https://play.google.com/*" works for the whitelist.

**Comment by TheW0LVERIN3** [comment]
It seems this was accidentally reopened.
Google Play Music doesn't exist anymore.

**Comment by hensm** [comment]
Oh, I was just reopening all compat issues instead of closing them when they were marked compatible so people didn't miss them if they went looking, but you're right, it doesn't make sense for this one.
